import { instr } from '../index.js';

function generateType(obj, indent = '') {
  const lines = [];

  for (const key of Object.keys(obj)) {
    const value = obj[key];
    if (typeof value === 'number') {
      // Format as hex, e.g. 0x0b
      const hex = '0x' + value.toString(16).toLowerCase().padStart(2, '0');
      lines.push(`${indent}  readonly ${key}: ${hex};`);
    } else if (typeof value === 'object' && value !== null) {
      lines.push(`${indent}  ${key}: {`);
      lines.push(generateType(value, indent + '  '));
      lines.push(`${indent}  };`);
    }
  }
  return lines.join('\n');
}

console.log('// Autogenerated by scripts/gen_instr_type.js. Do not edit manually.');
console.log('export const instr: {');
console.log(generateType(instr));
console.log('};\n// End of autogenerated instruction types.');
